# Generated by Django 5.2.4 on 2025-07-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="symbol",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="recurringtransaction",
            name="description",
            field=models.TextField(blank=True, default="null"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
