# Generated by Django 5.1.5 on 2025-07-05 06:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('updated_at', models.DateTimeField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('Health', 'Physical and Health'), ('Finance', 'Financial and Cash Flow'), ('Hobby', 'Recreational, Hobbies and Vacations'), ('Work', 'Work, Vocational and Volunteer Involvement'), ('Romance', 'Relational Romance and significant Other'), ('Family', 'Family and Inner Circle'), ('Friend', 'Friends and Social Circle'), ('Spiritual', 'Spiritual and Personal Growth')], max_length=10, verbose_name='Areas of Life')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
                'ordering': ['name'],
            },
        ),
    ]
